# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rui Liu
name: Rui Liu
position: Ph.D. student 
email: ruiliu@umd.edu
description: >-
  I am a Ph.D. student in [Computer Science](https://www.cs.umd.edu/) at the University of Maryland, College Park, working with Prof. [Pratap Tokekar](http://tokekar.com) and Prof. [Ming Lin](https://www.cs.umd.edu/~lin). 
  Previously, I earned my bachelor's degree from [Shanghai Jiao Tong University](https://en.sjtu.edu.cn/). I have also interned at Apple and Tencent Robotics X. 

  
  # My research focuses on developing robust and adaptive learning algorithms for autonomous systems. 
  I work on Multimodal Learning, Imitation Learning, and Reinforcement Learning etc. My goal is to advance AI-driven decision-making by improving efficiency, generalization, and robustness in real-world scenarios, such as Robotics and Autonomous Driving. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ruiiu.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: KeunhongP
# github_username: ruiiu
google_scholar: pMeiokwAAAAJ&hl
# google_analytics: G-MFWSBLRKG0

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
